# Generated by Django 4.2.7 on 2025-04-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xmu", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("authors", models.CharField(max_length=300)),
                ("link", models.URLField(max_length=500)),
            ],
        ),
    ]
