# Generated by Django 4.2.7 on 2025-04-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xmu", "0002_paper"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchDirection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("direction_name", models.TextField()),
            ],
        ),
    ]
