# Generated by Django 4.2.7 on 2025-04-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xmu", "0004_galleryimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryimage",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
