# Generated by Django 4.2.7 on 2025-04-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xmu", "0005_galleryimage_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResultImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="result_images/")),
                ("weight", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
