# Generated by Django 5.2 on 2025-04-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xmu", "0006_resultimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="published_date",
            field=models.DateTimeField(null=True),
        ),
    ]
