# Generated by Django 5.2 on 2025-04-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xmu", "0007_paper_published_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="members/")),
            ],
        ),
    ]
