# Generated by Django 5.2 on 2025-04-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xmu", "0008_member"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="image",
        ),
        migrations.RemoveField(
            model_name="member",
            name="role",
        ),
        migrations.AddField(
            model_name="member",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="member",
            name="degree",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="education",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="position",
            field=models.CharField(
                choices=[("Professor", "Professor"), ("Member", "Member")],
                default="Member",
                max_length=10,
            ),
        ),
    ]
