# Generated by Django 5.2 on 2025-04-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xmu", "0009_remove_member_image_remove_member_role_member_avatar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="weight",
            field=models.IntegerField(default=0),
        ),
    ]
