# Generated by Django 5.2 on 2025-04-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xmu", "0010_member_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="avatar",
            field=models.ImageField(
                blank=True, default="avatar.jpg", null=True, upload_to="avatars/"
            ),
        ),
    ]
