# Generated by Django 4.2.7 on 2025-04-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xmu", "0011_alter_member_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackgroundImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, default="logo.jpg", null=True, upload_to="bg/"
                    ),
                ),
                ("weight", models.IntegerField(default=0)),
                ("quote", models.TextField(blank=True, null=True)),
                ("author", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
