# Generated by Django 4.2.7 on 2025-04-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xmu", "0012_backgroundimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backgroundimage",
            name="author",
            field=models.CharField(default="Isaac Newton", max_length=100),
        ),
        migrations.AlterField(
            model_name="backgroundimage",
            name="quote",
            field=models.TextField(
                blank=True,
                default="If I have seen further it is by standing on the shoulders of giants.",
                null=True,
            ),
        ),
    ]
