# Generated by Django 5.2 on 2025-06-10 06:44

import xmu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xmu", "0014_alter_backgroundimage_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to=xmu.models.user_directory_path)),
                ("title", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
